In [2]:
import numpy as np
a = np.array([1,2,3])
print(a)

[1 2 3]


In [5]:
print(np.__version__)
np.show_config()

1.14.3
mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/dell/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2016.4.246\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2016.4.246\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2016.4.246\\windows\\mkl\\lib', 'C:/Users/dell/Anaconda3\\Library\\include']
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/dell/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2016.4.246\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2016.4.246\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2016.4.246\\windows\\mkl\\lib', '

In [7]:
a = np.zeros(10)
print(a)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [25]:
a = np.zeros((2,10))
print(a)
print("%d bytes"%(a.size*a.itemsize))

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
160 bytes


In [8]:
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.  If ``x1.shape != x2.shape``, they must be
    broadcastable to a common shape (which may be the shape of one or
    the other).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or `None`,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    Values of True indicate to calculate the ufunc at that position, values
    of False indicate to leave the value in the output alone.
**kwargs
    For other keyword-only arguments, see the
    :ref:`ufunc docs <ufuncs.kwargs>`.

Returns
-------
add : ndarray or scalar
    The

In [10]:
a = np.zeros(10)
a[4] = 1
print(a)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [12]:
a = np.arange(10,50)
print(a)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [13]:
a = a[::-1]
print(a)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


In [15]:
a = np.arange(9)
a = a.reshape(3,3)
print(a)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [26]:
na = np.nonzero([1,2,0,0,4,0])
print(na)

(array([0, 1, 4], dtype=int64),)


In [27]:
Z = np.eye(3)
print(Z)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [28]:
b = np.random.random((3,3,3))
print(b)

[[[0.54257832 0.43971152 0.29454588]
  [0.5189853  0.32758413 0.62968028]
  [0.19470281 0.39591569 0.08628527]]

 [[0.80029115 0.90324414 0.5586534 ]
  [0.14160164 0.03695378 0.58560332]
  [0.99820446 0.38257324 0.59948766]]

 [[0.49264565 0.24732109 0.31183086]
  [0.12065944 0.93126866 0.4675616 ]
  [0.54000919 0.7663597  0.55147875]]]


In [30]:
b = np.random.random((10,10))
b_max = b.max()
b_min = b.min()
print(b,b_max,b_min)

[[0.42907067 0.66740675 0.30641319 0.83093874 0.40941728 0.94495933
  0.91037913 0.6437111  0.49866064 0.7742161 ]
 [0.05930166 0.96347545 0.88337522 0.13015119 0.59972685 0.88607312
  0.41097939 0.01848845 0.09492609 0.0197232 ]
 [0.9976879  0.87206741 0.03680336 0.65884951 0.03055686 0.90738498
  0.41195583 0.66355036 0.31090957 0.26466597]
 [0.58809672 0.344545   0.39503369 0.13944254 0.73691313 0.68752867
  0.16391715 0.42910475 0.27865748 0.69279909]
 [0.07872883 0.85902936 0.37303305 0.70584812 0.05657309 0.58822291
  0.8227514  0.12307779 0.27702841 0.10477515]
 [0.57874456 0.15527666 0.70883042 0.99187175 0.90367885 0.47906061
  0.15691338 0.07166741 0.10256879 0.82198854]
 [0.5516763  0.81722986 0.19499452 0.40927343 0.35358147 0.21744929
  0.99811151 0.63322804 0.76082723 0.254773  ]
 [0.62273211 0.51185198 0.44235825 0.73670606 0.08082087 0.5945055
  0.72184764 0.34991257 0.51614474 0.78148319]
 [0.35887084 0.95590217 0.40371514 0.82394539 0.0728565  0.0674739
  0.73016247 0

In [31]:
a = np.random.random(30)
a_mean = a.mean()
print(a_mean)

0.480105466118161


In [33]:
b = np.ones((10,10))
b[1:-1,1:-1] = 0
print(b)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [34]:
c = np.pad(b, pad_width=1, mode='constant', constant_values=0)
print(c)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [35]:
print(0 * np.nan)

nan


In [36]:
print(np.nan == np.nan)

False


In [37]:
print(np.inf > np.nan)

False


In [38]:
print(np.nan - np.nan)

nan


In [39]:
print(0.3 == 3 * 0.1)

False


In [40]:
b = np.diag(1+np.arange(4),k=-1)
print(b)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


In [41]:
b = np.zeros((8,8),dtype=int)
b[1::2,::2] = 1
b[::2,1::2] = 1
print(b)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [42]:
print(np.unravel_index(100,(6,7,8)))

(1, 5, 4)


In [43]:
b = np.tile( np.array([[0,1],[1,0]]), (4,4))
print(b)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [44]:
b = np.random.random((5,5))
bmax, bmin = b.max(), b.min()
b = (b - bmin)/(bmax - bmin)
print(b)

[[0.28547893 0.40196474 0.16956594 0.20011475 0.90022956]
 [0.91156736 0.72721542 0.77077493 0.38676126 0.58375067]
 [0.95278548 0.52054913 0.35865163 0.7484784  0.35862133]
 [0.25397344 0.39229956 0.         1.         0.60647795]
 [0.81301708 0.06143366 0.5639338  0.91504207 0.67989422]]


In [45]:
color = np.dtype([("r", np.ubyte, 1),
                  ("g", np.ubyte, 1),
                  ("b", np.ubyte, 1),
                  ("a", np.ubyte, 1)])
color

dtype([('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')])

In [46]:
b = np.dot(np.ones((5,3)), np.ones((3,2)))
print(b)

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


In [47]:
b = np.arange(11)
b[(3 < b) & (b <= 8)] *= -1
print(b)

[ 0  1  2  3 -4 -5 -6 -7 -8  9 10]


In [48]:
print(sum(range(5),-1))

9


In [49]:
from numpy import *
print(sum(range(5),-1))

10


In [51]:
b = np.arange(5)
b ** b  # legal

array([  1,   1,   4,  27, 256], dtype=int32)

In [52]:
b = np.arange(5)
2 << b>> 2  # false

array([0, 1, 2, 4, 8], dtype=int32)

In [53]:
b = np.arange(5)
b <- b   # legal

array([False, False, False, False, False])

In [54]:
b = np.arange(5)
1j*b   # legal

array([0.+0.j, 0.+1.j, 0.+2.j, 0.+3.j, 0.+4.j])

In [55]:
b = np.arange(5)
b/1/1   # legal

array([0., 1., 2., 3., 4.])

In [56]:
b = np.arange(5)
b<b>b    # false

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [57]:
print(np.array(0) / np.array(0))

nan


C:\Users\dell\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


In [58]:
print(np.array(0) // np.array(0))

0


C:\Users\dell\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in floor_divide
  """Entry point for launching an IPython kernel.


In [59]:
print(np.array([np.nan]).astype(int).astype(float))

[-2.14748365e+09]


In [60]:
b = np.random.uniform(-10,+10,10)
print (np.copysign(np.ceil(np.abs(b)),b))

[ 10.   9.   5.   5. -10.  -9.   3.  -4. -10.  -8.]


In [61]:
b1 = np.random.randint(0,10,10)
b2= np.random.randint(0,10,10)
print(np.intersect1d(b1,b2))

[0 1 4 5 7 8]


In [62]:
# Suicide mode on
defaults = np.seterr(all="ignore")
Z = np.ones(1) / 0

# Back to sanity
_ = np.seterr(**defaults)

An equivalent way, with a context manager:

with np.errstate(divide='ignore'):
    Z = np.ones(1) / 0

SyntaxError: invalid syntax (<ipython-input-62-0437b6d2f8fa>, line 8)

In [63]:
np.sqrt(-1) == np.emath.sqrt(-1)  # False

C:\Users\dell\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in sqrt
  """Entry point for launching an IPython kernel.


False

In [64]:
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
today     = np.datetime64('today', 'D')
tomorrow  = np.datetime64('today', 'D') + np.timedelta64(1, 'D')
print ("Yesterday is " + str(yesterday))
print ("Today is " + str(today))
print ("Tomorrow is "+ str(tomorrow))

Yesterday is 2019-08-06
Today is 2019-08-07
Tomorrow is 2019-08-08


In [65]:
Z = np.arange('2016-07', '2016-08', dtype='datetime64[D]')
print(Z)


['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


In [66]:
A = np.ones(3)*1
B = np.ones(3)*2
C = np.ones(3)*3
np.add(A,B,out=B)

array([3., 3., 3.])

In [67]:
np.divide(A,2,out=A)

array([0.5, 0.5, 0.5])

In [68]:
np.negative(A,out=A)

array([-0.5, -0.5, -0.5])

In [69]:
np.multiply(A,B,out=A)

array([-1.5, -1.5, -1.5])

In [70]:
Z = np.random.uniform(0,10,10)
print (Z - Z%1)

[7. 8. 1. 0. 0. 5. 2. 6. 9. 1.]


In [71]:
print (np.floor(Z))

[7. 8. 1. 0. 0. 5. 2. 6. 9. 1.]


In [72]:
print (np.ceil(Z)-1)

[7. 8. 1. 0. 0. 5. 2. 6. 9. 1.]


In [73]:
print (Z.astype(int))

[7 8 1 0 0 5 2 6 9 1]


In [74]:
print (np.trunc(Z))

[7. 8. 1. 0. 0. 5. 2. 6. 9. 1.]


In [75]:
Z = np.zeros((5,5))
Z += np.arange(5)
print (Z)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


In [77]:
def generate():
     for x in range(10):
            yield x
Z = np.fromiter(generate(),dtype=float,count=-1)
print (Z)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


In [78]:
Z = np.linspace(0,1,11,endpoint=False)[1:]
print (Z)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


In [79]:
Z = np.random.random(10)
Z.sort()
print (Z)

[0.09188836 0.11001575 0.188392   0.37013483 0.38040503 0.38178306
 0.4070471  0.49499594 0.6938985  0.78688633]


In [80]:
Z = np.arange(10)
np.add.reduce(Z)

45

In [81]:
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)
equal = np.allclose(A,B)
print(equal)

False


In [82]:
equal = np.array_equal(A,B)
print(equal)

False


In [83]:
Z = np.zeros(10)
Z.flags.writeable = False
Z[0] = 1

ValueError: assignment destination is read-only

In [84]:
Z = np.random.random((10,2))
X,Y = Z[:,0], Z[:,1]
R = np.sqrt(X**2+Y**2)
T = np.arctan2(Y,X)
print (R)
print (T)

[0.90639276 1.12789021 0.19450914 0.69953144 1.00285594 0.90970167
 0.39626842 0.80332068 1.01728913 0.52297071]
[0.90827888 0.73181028 0.99640434 0.07588626 1.36358977 1.44088863
 0.8960757  0.18638088 0.77400929 0.32063698]


In [85]:
Z = np.random.random(10)
Z[Z.argmax()] = 0
print (Z)

[0.29332866 0.65689475 0.24956645 0.71951881 0.78353698 0.09190049
 0.49027035 0.21265607 0.         0.01739053]


In [86]:
Z = np.zeros((5,5), [('x',float),('y',float)])
Z['x'], Z['y'] = np.meshgrid(np.linspace(0,1,5),np.linspace(0,1,5))
print(Z)

[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]


In [87]:
X = np.arange(8)
Y = X + 0.5
C = 1.0 / np.subtract.outer(X, Y)
print(np.linalg.det(C))

3638.1636371179666


In [91]:
for dtype in [np.int8, np.int32, np.int64]:
     print(np.iinfo(dtype).min)
     print(np.iinfo(dtype).max)
for dtype in [np.float32, np.float64]:
     print(np.finfo(dtype).min)
     print(np.finfo(dtype).max)
     print(np.finfo(dtype).eps)


-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


In [92]:
np.set_printoptions(threshold=np.nan)
Z = np.zeros((16,16))
print (Z)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [93]:
Z = np.arange(100)
v = np.random.uniform(0,100)
index = (np.abs(Z-v)).argmin()
print (Z[index])

79
